### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by pitmonticone**
This PR removes unused imports and useless `f` in strings.

### CODE REVIEW

**Comment by adyang1** [comment]
Thanks for this! I agree that all the removed f in strings are redundant, however some imports like "parent" in benchmarks/benchmark_polytope.py are currently used to access python files in the parent directory (in this case it allows one to import the Polytope class. The way this is implemented is hacky but I haven't figured out a way to cleanly import from parent directories - do you have any suggestions?

**Comment by pitmonticone** [comment]
> I agree that all the removed f in strings are redundant, however some imports like "parent" in benchmarks/benchmark_polytope.py are currently used to access python files in the parent directory (in this case it allows one to import the Polytope class). 

Maybe I could leave the `parent` import for the moment and merge the PR. Do you agree? @adyang1 

> This implementation is hacky but I haven't figured out a way to cleanly import from parent directories - do you have any suggestions?

I will look into it during the weekend and will let you know.

**Comment by pitmonticone** [comment]
I have reverted my `parent` removal now. 

I think that what you want can be achieved by setting up the `__init__.py` files. By adding `__init__.py` files the whole python directory becomes a package, making imports across sub-directories straightforward and eliminating the need for path modifications.

In the case of `benchmark_polytope` for example, you just need to add `__init__.py` in the `python` directory to make it the root package and then 

```python
from ..polytope import Polytope
from ..region import Region
```

where `..` goes up one level to the parent package `python`.

**Comment by pitmonticone** [comment]
I can do it right now.

**Comment by pitmonticone** [comment]
Ok, I have removed the `parent.py` hack and correctly imported the python modules contained in the parent repository as shown above.

**Comment by adyang1** [comment]
Wow that's great! That's a nice solution - all in agreement.

**Pull request merged**
